import BGS.HasseWeil.FunctionFieldNormalClosureRatFuncEquiv

#print axioms BGS.HasseWeil.functionFieldNormalClosureConstantCompositum
#print axioms BGS.HasseWeil.functionFieldNormalClosureConstantCompositum_fixingSubgroup
#print axioms BGS.HasseWeil.functionFieldNormalClosureConstantBase_eq_compositum
#print axioms BGS.HasseWeil.functionFieldNormalClosureConstantBaseX
#print axioms BGS.HasseWeil.functionFieldNormalClosureConstantBase_constantTower
#print axioms BGS.HasseWeil.functionFieldNormalClosureConstantBaseX_transcendental
#print axioms BGS.HasseWeil.functionFieldNormalClosureConstantBase_adjoin_X
#print axioms BGS.HasseWeil.functionFieldNormalClosureConstantBaseRatFuncAlgEquiv
#print axioms BGS.HasseWeil.functionFieldNormalClosureConstantBaseRatFuncAlgHom
#print axioms BGS.HasseWeil.functionFieldNormalClosureConstantBaseRatFuncAlgHom_surjective
#print axioms BGS.HasseWeil.functionFieldNormalClosureConstantBaseRatFuncAlgEquiv_X
