import BGS.HasseWeil.FiniteExtensionPlaceTower

#print axioms BGS.HasseWeil.finitePlaceUnder_under
#print axioms BGS.HasseWeil.finitePlaceUnder_surjective
#print axioms BGS.HasseWeil.infinityPlaceUnder_surjective
#print axioms BGS.HasseWeil.placeUnder_surjective
#print axioms BGS.HasseWeil.finitePlaceUnderFiberEquivPrimesOver
#print axioms BGS.HasseWeil.infinityPlaceUnderFiberEquivPrimesOver
#print axioms BGS.HasseWeil.sum_finitePlaceUnderFiber_ramification_inertia_eq_field_finrank
#print axioms BGS.HasseWeil.sum_infinityPlaceUnderFiber_ramification_inertia_eq_field_finrank
#print axioms BGS.HasseWeil.exists_gal_smul_finitePlace_asIdeal_of_same_under
#print axioms BGS.HasseWeil.exists_gal_smul_infinityPlace_asIdeal_of_same_under
#print axioms BGS.HasseWeil.finitePlaceRelative_ramificationIdx_inertiaDeg_eq_of_same_under
#print axioms BGS.HasseWeil.infinityPlaceRelative_ramificationIdx_inertiaDeg_eq_of_same_under
#print axioms BGS.HasseWeil.finitePlaceUnderFiber_card_mul_ramificationIdx_mul_inertiaDeg_eq_field_finrank
#print axioms BGS.HasseWeil.infinityPlaceUnderFiber_card_mul_ramificationIdx_mul_inertiaDeg_eq_field_finrank
#print axioms BGS.HasseWeil.finitePlaceInertiaGroup_card_eq_ramificationIdx
#print axioms BGS.HasseWeil.finitePlaceDecompositionGroup_card_eq_ramificationIdx_mul_inertiaDeg
#print axioms BGS.HasseWeil.infinityPlaceInertiaGroup_card_eq_ramificationIdx
#print axioms BGS.HasseWeil.infinityPlaceDecompositionGroup_card_eq_ramificationIdx_mul_inertiaDeg
#print axioms BGS.HasseWeil.sum_card_finitePlaceUnderFiberFixedBy_eq_card_galoisGroup
#print axioms BGS.HasseWeil.sum_card_infinityPlaceUnderFiberFixedBy_eq_card_galoisGroup
